services:
  db:
    container_name: machado_postgres
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/machado
    volumes:
      - pgdata:/var/lib/postgresql/data/machado
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  elasticsearch:
    container_name: machado_elasticsearch
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - discovery.type=single-node
    mem_limit: 1Gb
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ecdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  ecdata: