name: Machado CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python setup.py install
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 machado
    - name: Run migrations
      run: |
        python manage.py migrate
    - name: Run Tests
      run: |
        python manage.py test machado --settings machado.tests.settings
